/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRenderRouteImport } from './routes/api/render'
import { Route as PreviewsTemplateNameVariantRouteImport } from './routes/previews/$templateName/$variant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewsTemplateNameVariantRoute =
  PreviewsTemplateNameVariantRouteImport.update({
    id: '/previews/$templateName/$variant',
    path: '/previews/$templateName/$variant',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/render': typeof ApiRenderRoute
  '/previews/$templateName/$variant': typeof PreviewsTemplateNameVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/render': typeof ApiRenderRoute
  '/previews/$templateName/$variant': typeof PreviewsTemplateNameVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/render': typeof ApiRenderRoute
  '/previews/$templateName/$variant': typeof PreviewsTemplateNameVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/render' | '/previews/$templateName/$variant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/render' | '/previews/$templateName/$variant'
  id: '__root__' | '/' | '/api/render' | '/previews/$templateName/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRenderRoute: typeof ApiRenderRoute
  PreviewsTemplateNameVariantRoute: typeof PreviewsTemplateNameVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previews/$templateName/$variant': {
      id: '/previews/$templateName/$variant'
      path: '/previews/$templateName/$variant'
      fullPath: '/previews/$templateName/$variant'
      preLoaderRoute: typeof PreviewsTemplateNameVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRenderRoute: ApiRenderRoute,
  PreviewsTemplateNameVariantRoute: PreviewsTemplateNameVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
